require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
  Pry.start
end

desc "says hello"
task :helloworld do
  puts "hello world"
end
